### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by ashwin100196** [schlerp/flowpy#1]
Hi @schlerp , I happened to come across your medium article and had a similar idea parked for a while now: to profile existing data processing pipelines/scripts/notebooks to build a representation of the data flow. I believe this could be a future feature to this module, so this is very exciting to me. I work in Data Science and would find this extremely useful.

I'd like to contribute to adding new features on the pandas front, since I do not know much on the UI side of things. A few regular operations I use are listed below:

1. Basic feature/column computations
2. Aggregation using groupby
3.  Resampling time indices
4. Replacing and imputing values
5. Pivot, melt and stacking

Before I try to modify anything, I'd like to know if there's a tracker of sorts for current development activity and upcoming features already being worked on.

**Comment by schlerp** [comment]
Excellent! I was hoping I'd find some people to work with. I don't currently have a project set up for managing issues but they aren't hard to set up here on GitHub. 

Have you done much development work as part of a team before or contributed to open source software on GitHub? (It's not a problem if you haven't).

I think to start with can you please submit each of your feature requests as a seperate issue. Treat each issue as if it's it's own topic for discussion (please don't limit yourself to just feature requests if you have other concerns, raise an issue). I'll set up a project for this repository, tag the issues appropriately and then we can go from there!

Thanks for reaching out and I'm looking forward to developing with you!

**Comment by ashwin100196** [comment]
That's great, I have gone ahead and created separate issues for a set of features that can be started with. 

I have collaborated with teams in my organization for development, but haven't contributed to any Open Source software. So please let me know if there's something I am not doing right.

Thanks for your inputs, I am excited to work on this together too!
